
import { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, Calculator, X } from 'lucide-react';
import { useScraperStore } from '@/stores/scraper-store';
import { PDFDocument, rgb } from 'pdf-lib';
import { toast } from 'sonner';

const CalculatorWidget = () => {
    const [isVisible, setIsVisible] = useState(true);
    const { dppTotal, ppnTotal, selectedCount } = useScraperStore();

    // Formatting helper
    const fmt = (n: number) => new Intl.NumberFormat('id-ID').format(n);

    const handleExport = () => {
        // Mock data logic: if no rows selected, assume we are testing and generate mock data
        const count = selectedCount || 1;
        const isMock = selectedCount === 0;

        const mockData = Array.from({ length: count }).map((_, i) => ({
            invoiceNumber: `010.000-24.0000000${i}`,
            taxPeriod: '12-2024',
            transactionDate: '2024-12-26',
            // If dppTotal is 0 (mock), generate random amounts between 1M and 10M
            dpp: isMock ? Math.floor(Math.random() * 9000000) + 1000000 : dppTotal / count,
            ppn: isMock ? Math.floor(Math.random() * 900000) + 100000 : ppnTotal / count
        }));

        import('@/services/excel-export').then(mod => {
            mod.exportToExcel(mockData, isMock ? `CoreTax_Mock_Export_${Date.now()}.xlsx` : undefined);
            if (isMock) toast.info("Exported mock Excel file for testing.");
        });
    };

    const handleDownloadPDFs = async () => {
        if (!selectedCount) {
            // MOCK MODE: Generate a dummy PDF client-side
            try {
                toast.info("Generating mock PDF for testing...");
                const pdfDoc = await PDFDocument.create();
                const page = pdfDoc.addPage([600, 400]);
                page.drawText('This is a MOCK PDF generated by CoreTax Assist', {
                    x: 50,
                    y: 350,
                    size: 24,
                    color: rgb(0, 0.53, 0.71),
                });
                page.drawText(`Generated at: ${new Date().toLocaleString()}`, {
                    x: 50,
                    y: 300,
                    size: 12,
                });

                const pdfBytes = await pdfDoc.save();
                const blob = new Blob([pdfBytes as any], { type: 'application/pdf' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `CoreTax_Mock_Invoice_${Date.now()}.pdf`;
                a.click();
                URL.revokeObjectURL(url);
                toast.success("Mock PDF downloaded", { description: "Since no rows were selected, a dummy file was generated." });
            } catch (error) {
                console.error("Mock PDF generation failed", error);
                toast.error("Failed to generate mock PDF");
            }
            return;
        }

        // REAL MODE: Queue downloads via background script
        const mockFiles = Array.from({ length: selectedCount }).map((_, i) => ({
            url: 'https://coretaxdjp.pajak.go.id/fictional-pdf-' + i + '.pdf', // In real implementation, this would be real URLs scraper found
            filename: `010.000_2024_${i}.pdf`
        }));

        if (typeof chrome !== 'undefined' && chrome.runtime?.sendMessage) {
            chrome.runtime.sendMessage({ type: 'QUEUE_DOWNLOADS', data: mockFiles });
            toast.success(`Queued ${selectedCount} files for download`);
        } else {
            alert("Background download triggered (Mock)");
        }
    };

    if (!isVisible) return null;

    return (
        <div className="fixed bottom-6 right-6 z-[9999] font-sans antialiased animate-in fade-in slide-in-from-bottom-4 duration-300">
            <Card className="shadow-2xl border-t-4 border-t-brand-yellow w-[300px] bg-white">
                <div className="p-4 space-y-4">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="h-8 w-8 rounded-lg bg-brand-yellow/10 flex items-center justify-center">
                                <Calculator className="h-5 w-5 text-yellow-700" />
                            </div>
                            <div>
                                <h3 className="font-semibold text-sm text-brand-blue">Tax Calculator</h3>
                                <p className="text-xs text-slate-500">{selectedCount} rows selected</p>
                            </div>
                        </div>
                        <Button variant="ghost" size="icon" className="h-6 w-6 text-slate-400 hover:text-slate-600" onClick={() => setIsVisible(false)}>
                            <X className="h-4 w-4" />
                        </Button>
                    </div>

                    <div className="bg-slate-50 p-3 rounded-md space-y-1 border border-slate-100">
                        <div className="flex justify-between text-xs">
                            <span className="text-slate-500">Total DPP</span>
                            <span className="font-mono font-medium text-slate-700">{fmt(dppTotal)}</span>
                        </div>
                        <div className="flex justify-between text-xs">
                            <span className="text-slate-500">Total PPN</span>
                            <span className="font-mono font-medium text-slate-700">{fmt(ppnTotal)}</span>
                        </div>
                        <div className="h-px bg-slate-200 my-1" />
                        <div className="flex justify-between text-sm font-bold text-brand-blue">
                            <span>Total</span>
                            <span className="font-mono">{fmt(dppTotal + ppnTotal)}</span>
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-2">
                        <Button size="sm" className="w-full bg-brand-yellow text-brand-blue hover:bg-brand-yellow/90 font-semibold" onClick={handleExport}>
                            <Download className="mr-2 h-3 w-3" />
                            To Excel
                        </Button>
                        <Button size="sm" variant="outline" className="w-full border-slate-200 text-slate-600 bg-white hover:bg-slate-50 hover:text-brand-blue" onClick={handleDownloadPDFs}>
                            Get PDFs
                        </Button>
                    </div>
                </div>
            </Card>
        </div>
    );
};

export default CalculatorWidget;
